/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleTemplatesRouteImport } from './routes/console.templates'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsolePoliciesRouteImport } from './routes/console.policies'
import { Route as ConsoleKnowledgeRouteImport } from './routes/console.knowledge'
import { Route as ConsoleDeploymentRouteImport } from './routes/console.deployment'
import { Route as ConsoleCapabilitiesRouteImport } from './routes/console.capabilities'
import { Route as ConsoleAuditRouteImport } from './routes/console.audit'
import { Route as ConsoleAgentRouteImport } from './routes/console.agent'
import { Route as ConsoleEmployeesIndexRouteImport } from './routes/console.employees.index'
import { Route as ConsoleEmployeesNewRouteImport } from './routes/console.employees.new'
import { Route as ConsoleEmployeesIdRouteImport } from './routes/console.employees.$id'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTemplatesRoute = ConsoleTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePoliciesRoute = ConsolePoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleKnowledgeRoute = ConsoleKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeploymentRoute = ConsoleDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCapabilitiesRoute = ConsoleCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAgentRoute = ConsoleAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEmployeesIndexRoute = ConsoleEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEmployeesNewRoute = ConsoleEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEmployeesIdRoute = ConsoleEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/architecture': typeof ArchitectureRoute
  '/capabilities': typeof CapabilitiesRoute
  '/console': typeof ConsoleRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/platform': typeof PlatformRoute
  '/policies': typeof PoliciesRoute
  '/console/agent': typeof ConsoleAgentRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/capabilities': typeof ConsoleCapabilitiesRoute
  '/console/deployment': typeof ConsoleDeploymentRoute
  '/console/knowledge': typeof ConsoleKnowledgeRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/employees/$id': typeof ConsoleEmployeesIdRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/employees/': typeof ConsoleEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/architecture': typeof ArchitectureRoute
  '/capabilities': typeof CapabilitiesRoute
  '/employees': typeof EmployeesRoute
  '/platform': typeof PlatformRoute
  '/policies': typeof PoliciesRoute
  '/console/agent': typeof ConsoleAgentRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/capabilities': typeof ConsoleCapabilitiesRoute
  '/console/deployment': typeof ConsoleDeploymentRoute
  '/console/knowledge': typeof ConsoleKnowledgeRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console': typeof ConsoleIndexRoute
  '/console/employees/$id': typeof ConsoleEmployeesIdRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/employees': typeof ConsoleEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/architecture': typeof ArchitectureRoute
  '/capabilities': typeof CapabilitiesRoute
  '/console': typeof ConsoleRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/platform': typeof PlatformRoute
  '/policies': typeof PoliciesRoute
  '/console/agent': typeof ConsoleAgentRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/capabilities': typeof ConsoleCapabilitiesRoute
  '/console/deployment': typeof ConsoleDeploymentRoute
  '/console/knowledge': typeof ConsoleKnowledgeRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/employees/$id': typeof ConsoleEmployeesIdRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/employees/': typeof ConsoleEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent'
    | '/architecture'
    | '/capabilities'
    | '/console'
    | '/employees'
    | '/platform'
    | '/policies'
    | '/console/agent'
    | '/console/audit'
    | '/console/capabilities'
    | '/console/deployment'
    | '/console/knowledge'
    | '/console/policies'
    | '/console/settings'
    | '/console/templates'
    | '/console/'
    | '/console/employees/$id'
    | '/console/employees/new'
    | '/console/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent'
    | '/architecture'
    | '/capabilities'
    | '/employees'
    | '/platform'
    | '/policies'
    | '/console/agent'
    | '/console/audit'
    | '/console/capabilities'
    | '/console/deployment'
    | '/console/knowledge'
    | '/console/policies'
    | '/console/settings'
    | '/console/templates'
    | '/console'
    | '/console/employees/$id'
    | '/console/employees/new'
    | '/console/employees'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent'
    | '/architecture'
    | '/capabilities'
    | '/console'
    | '/employees'
    | '/platform'
    | '/policies'
    | '/console/agent'
    | '/console/audit'
    | '/console/capabilities'
    | '/console/deployment'
    | '/console/knowledge'
    | '/console/policies'
    | '/console/settings'
    | '/console/templates'
    | '/console/'
    | '/console/employees/$id'
    | '/console/employees/new'
    | '/console/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentRoute: typeof AgentRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  PlatformRoute: typeof PlatformRoute
  PoliciesRoute: typeof PoliciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/templates': {
      id: '/console/templates'
      path: '/templates'
      fullPath: '/console/templates'
      preLoaderRoute: typeof ConsoleTemplatesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/policies': {
      id: '/console/policies'
      path: '/policies'
      fullPath: '/console/policies'
      preLoaderRoute: typeof ConsolePoliciesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/knowledge': {
      id: '/console/knowledge'
      path: '/knowledge'
      fullPath: '/console/knowledge'
      preLoaderRoute: typeof ConsoleKnowledgeRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/deployment': {
      id: '/console/deployment'
      path: '/deployment'
      fullPath: '/console/deployment'
      preLoaderRoute: typeof ConsoleDeploymentRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/capabilities': {
      id: '/console/capabilities'
      path: '/capabilities'
      fullPath: '/console/capabilities'
      preLoaderRoute: typeof ConsoleCapabilitiesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/agent': {
      id: '/console/agent'
      path: '/agent'
      fullPath: '/console/agent'
      preLoaderRoute: typeof ConsoleAgentRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/employees/': {
      id: '/console/employees/'
      path: '/employees'
      fullPath: '/console/employees/'
      preLoaderRoute: typeof ConsoleEmployeesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/employees/new': {
      id: '/console/employees/new'
      path: '/employees/new'
      fullPath: '/console/employees/new'
      preLoaderRoute: typeof ConsoleEmployeesNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/employees/$id': {
      id: '/console/employees/$id'
      path: '/employees/$id'
      fullPath: '/console/employees/$id'
      preLoaderRoute: typeof ConsoleEmployeesIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAgentRoute: typeof ConsoleAgentRoute
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleCapabilitiesRoute: typeof ConsoleCapabilitiesRoute
  ConsoleDeploymentRoute: typeof ConsoleDeploymentRoute
  ConsoleKnowledgeRoute: typeof ConsoleKnowledgeRoute
  ConsolePoliciesRoute: typeof ConsolePoliciesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleTemplatesRoute: typeof ConsoleTemplatesRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleEmployeesIdRoute: typeof ConsoleEmployeesIdRoute
  ConsoleEmployeesNewRoute: typeof ConsoleEmployeesNewRoute
  ConsoleEmployeesIndexRoute: typeof ConsoleEmployeesIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAgentRoute: ConsoleAgentRoute,
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleCapabilitiesRoute: ConsoleCapabilitiesRoute,
  ConsoleDeploymentRoute: ConsoleDeploymentRoute,
  ConsoleKnowledgeRoute: ConsoleKnowledgeRoute,
  ConsolePoliciesRoute: ConsolePoliciesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleTemplatesRoute: ConsoleTemplatesRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleEmployeesIdRoute: ConsoleEmployeesIdRoute,
  ConsoleEmployeesNewRoute: ConsoleEmployeesNewRoute,
  ConsoleEmployeesIndexRoute: ConsoleEmployeesIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentRoute: AgentRoute,
  ArchitectureRoute: ArchitectureRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  PlatformRoute: PlatformRoute,
  PoliciesRoute: PoliciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
